### ISSUE TITLE
Flip along horizontal axis

### ISSUE THREAD

**Issue by sunils27** [djk12587/DJKFlipper#2]
Thanks for the great library. 

Is it possible to extend this to flip along a horizontal axis as opposed to a vertical axis? If it already exists can you please provide an example/documentation. 

Thanks!

**Comment by djk12587** [comment]
Hi, someone else had the same question. This library wasn't built with vertical flips in mind so it's not supported as of now. It's on my to do list though. 

Below is a link where I go into some detail as to how to implement a vertical flip. 
https://github.com/djk12587/DJKFlipper/issues/1

**Comment by sunils27** [comment]
Hi,

I was wondering if you had any examples with dynamic arrays for the
flipView Array?

I'm pretty new to Swift, so I'm still figuring things out.

Thanks,
Sunil

**Comment by djk12587** [comment]
By dynamic array do you mean an array that is not type specific? 

In my example the flipperViewArray is an array of UIViewController types. If you wanted to you could use an array of UIViews instead or an NSMutableArray and put whatever type/subclass of UIView you want. The DJKFlipperView class only needs a collection of UIViews to work, how you serve DJKFlipperViews the UIViews is up to you.

**Comment by sunils27** [comment]
Thanks for your reply. I'm getting the hang of it now.

Sunil
