### ISSUE TITLE
Refreshing View, white background

### ISSUE THREAD

**Issue by husyn** [djk12587/DJKFlipper#3]
Hello,
I've just updated my project to this library from MPFlipViewController. And this is how I'm doing it:

`       VCArray.append(self.getVC(0))
        VCArray.append(self.getVC(1))
        VCArray.append(self.getVC(2))
        VCArray.append(self.getVC(3))
        VCArray.append(self.getVC(4))
        flipperView.dataSource = self
`
The issue is that my ViewController's are white when I flip and after a while the UI loads. The 1st ViewController is also white which holds these flip ViewControllers. If I flip and come back then its fine.
Most likely I'm doing a very silly mistake, but anybody can help ?

Thanks

**Comment by husyn** [comment]
I finally solved the issue. For reference here is the problem statement
`http://stackoverflow.com/questions/18156774/view-unusable-after-dismissviewcontrolleranimatedcompletion`
and DJKFlipperView.swift modifies the constraints (Don't know if it should or not but ) which is the issue.

**Comment by djk12587** [comment]
Thanks for posting this!
