### ISSUE TITLE
Pod not working in Swift 2.2

### ISSUE THREAD

**Issue by matiasvillaverde** [djk12587/DJKFlipper#4]
I try to add the pod in a project with Swift 2.2 and has a lot of deprecations like println().

**Comment by djk12587** [comment]
Sorry, I haven't touched this repo in a while, it was written in swift 1.2 I believe. Its hard to find time to update this because I am no longer using library in any of my current applications.

**Comment by djk12587** [comment]
not that I matters anymore but I finally updated to project to swift 3. I plan on using this in an application of mine so I plan on refactoring this project a lot.
