### ISSUE TITLE
pod not working in swift3

### ISSUE THREAD

**Issue by dia-mk** [djk12587/DJKFlipper#8]
I am trying to use the following code to install pods:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DJKFlipper'

After successful installation, when I open workspace, there are 113 issues and the build fails.

Please give me some solution.

**Comment by djk12587** [comment]
Oops, I forgot to update the pod spec file to 0.1.7 which supports swift 3. It should be up to date now. If you are still getting 0.1.6 be sure to run a `pod repo update` before your next `pod install`

**Comment by dia-mk** [comment]
So do we need platform to be 8.0 only?

**Comment by djk12587** [comment]
Yes, 8.0 and above. There is also a swift 4 branch if thats needed.

**Comment by dia-mk** [comment]
Great! Thanks!
