### ISSUE TITLE
Constraints not working properly - Swift 3

### ISSUE THREAD

**Issue by Mamtak1811** [djk12587/DJKFlipper#9]
I am using flipper inside a view controller having navigation bar and tab bar. For now, I have a label at the top and an image below in the flipper detail view. Whenever I put top constraints to label in the detail page view (PageTestViewController's IB, as referred to in your example), the view shifts slightly down after loading, during runtime. No shifting happens if I keep the image horizontally and vertically centered and remove the label totally. I am unable to understand what's exactly happening here. 

One more issue is that I need to load the flipview only once a button is clicked, not on page load. How to accomplish that?

**Comment by djk12587** [comment]
Any chance you can create a sample project that illustrates the problem you are having? I am having trouble picturing how your view hierarchy is set up.

**Comment by Mamtak1811** [comment]
Will share a demo project shortly

**Comment by Mamtak1811** [comment]
I have uploaded demo project to this link: https://www.dropbox.com/s/ikl5m266cc4on7t/Demo.zip?dl=0

**Comment by djk12587** [comment]
@Mamtak1811 thanks for uploading that. There seems to be something funky if you set up the `flipperView` via constraints. I'll have to look into that. A work around is to remove the flipperview from your `TopStoriesScene` and turn the viewcontrollers `view` into a `DJKFlipperView`. Also be sure to connect the outlet again. Check out the screen shot below.

![screenShot](http://i.imgur.com/2MJqG25.png)

**Comment by Mamtak1811** [comment]
I tried that too. It does not work with top constraints in the SportsScene.

**Comment by djk12587** [comment]
I see now. It seems creating the pages that flip in the storyboard cause issues. It has something to do with the `toplayoutguide` being set dynamically.

If you remove the `SportsFliperViewController` from the storyboard and create a separate `.xib` for it, it should honor the top constraint correctly.

**Comment by Mamtak1811** [comment]
Thanks! That works perfectly fine.

Please also answer this question:  I need to load the flipview only once a button is clicked, not on page load. How to accomplish that?

**Comment by djk12587** [comment]
@Mamtak1811 i'm glad that worked.

I pushed an update `0.1.9` setting the datasource no longer auto refreshes the view. You can set up your datasource and array, but call `reload()` whenever you want the flipperview to show.
